//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwJugueriaAgustin.ConsultaRuc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/WSConsultaRuc")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActividadComericioExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CondicionContribuyenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoContribuyenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaInicioActividadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaInscripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SistemaContabilidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SistemaEmisionComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoComtribuyenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActividadComericioExterior {
            get {
                return this.ActividadComericioExteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.ActividadComericioExteriorField, value) != true)) {
                    this.ActividadComericioExteriorField = value;
                    this.RaisePropertyChanged("ActividadComericioExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CondicionContribuyente {
            get {
                return this.CondicionContribuyenteField;
            }
            set {
                if ((object.ReferenceEquals(this.CondicionContribuyenteField, value) != true)) {
                    this.CondicionContribuyenteField = value;
                    this.RaisePropertyChanged("CondicionContribuyente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoContribuyente {
            get {
                return this.EstadoContribuyenteField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoContribuyenteField, value) != true)) {
                    this.EstadoContribuyenteField = value;
                    this.RaisePropertyChanged("EstadoContribuyente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicioActividad {
            get {
                return this.FechaInicioActividadField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaInicioActividadField, value) != true)) {
                    this.FechaInicioActividadField = value;
                    this.RaisePropertyChanged("FechaInicioActividad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInscripcion {
            get {
                return this.FechaInscripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaInscripcionField, value) != true)) {
                    this.FechaInscripcionField = value;
                    this.RaisePropertyChanged("FechaInscripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercial {
            get {
                return this.NombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComercialField, value) != true)) {
                    this.NombreComercialField = value;
                    this.RaisePropertyChanged("NombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SistemaContabilidad {
            get {
                return this.SistemaContabilidadField;
            }
            set {
                if ((object.ReferenceEquals(this.SistemaContabilidadField, value) != true)) {
                    this.SistemaContabilidadField = value;
                    this.RaisePropertyChanged("SistemaContabilidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SistemaEmisionComprobante {
            get {
                return this.SistemaEmisionComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.SistemaEmisionComprobanteField, value) != true)) {
                    this.SistemaEmisionComprobanteField = value;
                    this.RaisePropertyChanged("SistemaEmisionComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoComtribuyente {
            get {
                return this.TipoComtribuyenteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoComtribuyenteField, value) != true)) {
                    this.TipoComtribuyenteField = value;
                    this.RaisePropertyChanged("TipoComtribuyente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsultaRuc.IWsConsulta")]
    public interface IWsConsulta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsConsulta/ObtenerEmpresa", ReplyAction="http://tempuri.org/IWsConsulta/ObtenerEmpresaResponse")]
        SwJugueriaAgustin.ConsultaRuc.Empresa ObtenerEmpresa(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsConsulta/ObtenerEmpresa", ReplyAction="http://tempuri.org/IWsConsulta/ObtenerEmpresaResponse")]
        System.Threading.Tasks.Task<SwJugueriaAgustin.ConsultaRuc.Empresa> ObtenerEmpresaAsync(string ruc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsConsultaChannel : SwJugueriaAgustin.ConsultaRuc.IWsConsulta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsConsultaClient : System.ServiceModel.ClientBase<SwJugueriaAgustin.ConsultaRuc.IWsConsulta>, SwJugueriaAgustin.ConsultaRuc.IWsConsulta {
        
        public WsConsultaClient() {
        }
        
        public WsConsultaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsConsultaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsConsultaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SwJugueriaAgustin.ConsultaRuc.Empresa ObtenerEmpresa(string ruc) {
            return base.Channel.ObtenerEmpresa(ruc);
        }
        
        public System.Threading.Tasks.Task<SwJugueriaAgustin.ConsultaRuc.Empresa> ObtenerEmpresaAsync(string ruc) {
            return base.Channel.ObtenerEmpresaAsync(ruc);
        }
    }
}
